### ISSUE TITLE
Issue with 7015_pacemaker_version.check on RHEL

### ISSUE THREAD

**Issue by fdanapfel** [SAP/arp142-hana#255]
https://github.com/SAP/arp142-hana/blob/main/scripts/lib/check/7015_pacemaker_version.check

The check references Red Hat KCS 4849731 "Why does pacemaker stop the Slave of a SAPHana resource when pengine reports "Pre-allocation failed"? ((https://access.redhat.com/solutions/4849731) and based on this reports the following when a lower pacemaker version is installed on RHEL 8:

[C] L7015 <ERROR> pacemaker must be updated (SAP Note #1552925,Red Hat KB #4849731) (is: 2.1.5-9.4.el8_8, should be: >=2.1.6-8.el8)

Since pacemaker version 2.1.6-8.el8 is only available for RHEL 8.10 and Red Hat has no plans to backport the fix for this issue to previous RHEL 8 minor releases it wil not be possible for customers who have locked their RHEL 8 release to a lower RHEL 8 minor release  (for example 8.8) to implement the recommendation from the check.
 
The check apparently does not take into account that there is a workaround available for the issue documented in KCS 4849731:
"As a workaround for this issue, setting a default [resource-stickiness](https://access.redhat.com/solutions/1299213) will also avoid the warnings."

The Red Hat documentation for the HA solutions for SAP actually states that customers must set up resource defaults for resource-stickiness and migration-threshold:
HANA: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_for_sap_solutions/8/html/automating_sap_hana_scale-up_system_replication_using_the_rhel_ha_add-on/asmb_config_ha_cluster_automating-sap-hana-scale-up-system-replication
NetWeaver / S4HANA app servers: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_for_sap_solutions/8/html/configuring_ha_clusters_to_manage_sap_netweaver_or_sap_s4hana_application_server_instances_using_the_rhel_ha_add-on/asmb_set_cluster_v8-configuring-clusters-to-manage#con_config_general_cluster_v8-configuring-clusters-to-manage

It would therefore be good if the check could be enhanced to verify if customers have set a resource default for resource-stickiness and if that is not the case then customers should be adviset to set the default value for resource stickiness according to the documentation, instead of just telling customers tha they have to update the pacemaker version.

**Comment by fdanapfel** [comment]
I noticed tha there is another check that is referencing the same Red Hat KCS 4849731 but actually does check if the resource defaults are set: https://github.com/SAP/arp142-hana/blob/main/scripts/lib/check/7018_pacemaker_attributes.check

Therefore my recommendation would actually be to remove the checks for RHEL from https://github.com/SAP/arp142-hana/blob/main/scripts/lib/check/7015_pacemaker_version.check

**Comment by PeterPitterling** [comment]
setting resource stickiness is considered as workaround only - the solution would be the fix?! 

> Workaround
> As a workaround for this issue, setting a default [resource-stickiness](https://access.redhat.com/solutions/1299213) will also avoid the warnings.

will the workaround also prevent the secondary from the unnecessary restart?

**Comment by fdanapfel** [comment]
As mentioned at HANA: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_for_sap_solutions/8/html/automating_sap_hana_scale-up_system_replication_using_the_rhel_ha_add-on/asmb_config_ha_cluster_automating-sap-hana-scale-up-system-replication for HA cluster setups on RHEL for managing SAP HANA setting the defaullt for resource-stickiness is required for the cluster setup to work correctly.

So if customers have configured the setup according to those guidelines they should never see the issue described in  https://access.redhat.com/solutions/4849731 and therefore updating pacemaker is not required.

**Comment by fdanapfel** [comment]
We have now updated https://access.redhat.com/solutions/4849731 to hopefully make it more clear that this is not an issue that is specific to using the RHEL HA Add-On to manage SAP HANA, and also added some statements to try to explain that if  customers have configured the resource defaults according to our guidelines for setting up clusters for managing SAP HANA  then updating pacemaker is not needed.

And yes, if the resource default for resource-stickiness has been set up correctly it will prevent the secondary from the unnecessary restart.
